on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read  

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: "3dc46f31-fef5-4091-8ad5-5cd445268508"
          tenant-id: "7bd062fa-35e3-46b0-882e-1de9980dc2f8"
          subscription-id: "75146836-fdff-4091-9190-2ee9cca9c8b6"

      - name: Terraform Init with Backend
        run: |
          terraform init \
            -backend-config="resource_group_name=myrg" \
            -backend-config="storage_account_name=stgmahesh01" \
            -backend-config="container_name=mycon01" \
            -backend-config="key=dev.terraform.tfstate"
        working-directory: dev

      - name: Terraform Validate
        run: terraform validate
        working-directory: dev

      - name: Terraform Plan
        run: terraform plan
        working-directory: dev





      
    
                 


              
